export const SAGATYPE_HOME_SELECT_DIFFICULT = "SAGATYPE_HOME_SELECT_DIFFICULT";
export const SAGATYPE_HOME_SELECT_DIFFICULT_ASYNC = "SAGATYPE_HOME_SELECT_DIFFICULT_ASYNC";

export const SAGATYPE_GAME_MAP = "SAGATYPE_GAME_MAP";
export const SAGATYPE_GAME_MAP_ASYNC = "SAGATYPE_GAME_MAP_ASYNC";

export const SAGATYPE_GAME_SELECT_CELL = "SAGATYPE_GAME_SELECT_CELL";
export const SAGATYPE_GAME_SELECT_CELL_ASYNC = "SAGATYPE_GAME_SELECT_CELL_ASYNC";

export const SAGATYPE_GAME_NOTIF_MESSAGE = "SAGATYPE_GAME_NOTIF_MESSAGE";
export const SAGATYPE_GAME_CHANGE_ENDED = "SAGATYPE_GAME_CHANGE_ENDED";
export const SAGATYPE_GAME_CLEAR = "SAGATYPE_GAME_CLEAR";